--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/JoinFireworks
build-by-default: true
branches:
- main
projects:
  JoinFireworks:
    path: ""
    icon: "/assets/logo.png"
...
