---
# JoinFireworks Configuration
# Author: brokiem (https://github.com/brokiem)
# Source code: https://github.com/brokiem/JoinFireworks

# Fireworks flight duration in seconds (Default: 2)
flight-duration: 2

# Fireworks spawn delay after player joins in seconds (Default: 2)
spawn-delay: 2
...